# Generated by Django 5.0.7 on 2024-08-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="learning_language",
            field=models.CharField(default="fr", max_length=5),
        ),
        migrations.RemoveField(
            model_name="learnedword",
            name="language",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="native_language",
            field=models.CharField(default="en", max_length=5),
        ),
        migrations.DeleteModel(
            name="Language",
        ),
    ]
